WebStoreDALBLL/WebStoreDALBLL/Controllers/BestillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreDALBLL.Models;
using WebStoreDALBLL.BLL;

namespace WebStoreDALBLL.Controllers
{
    public class BestillingController : Controller
    {
        // GET: Bestilling
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListAllOrders()
        {
            
            var bestillingsDb = new BestillingsBLL();
            List<Bestilling> alleBestillinger = bestillingsDb.getAll();
            return View(alleBestillinger);
          
        }

        public ActionResult DetailsOrder(int id)
        {
            var BestillingsDb = new BestillingsBLL();
            Bestilling enBestilling = BestillingsDb.getSingleBestilling(id);
         
            return View(enBestilling);

        }

        public ActionResult DetailsOrderLines()//int id)
        {
            return View();

        }

        public ActionResult ListAllOrderlines()
        {
            var BestillingsDb = new BestillingsBLL();
            List<Ordrelinje> or = BestillingsDb.getAllOrdrelinjer();
            return View(or);
        }

        public ActionResult DetailsOrdreSum(int id)
        {
            return View();
        }

        public ActionResult OrderConfirmation()
        {
            Handlevogn hv = (Handlevogn)Session["Handlevogn"];
            var BestillingsDb = new BestillingsBLL();
            BestillingsDb.insertBestilling(hv);

            return View();
        }

        public ActionResult RegisterOrder()
        {
            if(((bool)Session["LoggetInn"])!= true)
            {
                return RedirectToAction("LoggInn", "Kunde");
            }
            Handlevogn hv = (Handlevogn)Session["Handlevogn"];
           
            return View(hv);
            
        }
    }
}

WebStoreDALBLL/WebStoreDALBLL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreDALBLL.BLL;
using WebStoreDALBLL.Models;

namespace WebStoreDALBLL.Controllers
{
    public class HomeController : Controller
    {
        // GET: Butikk
        public ActionResult Index()
        {
            if(Session["Handlevogn"] == null)
            {
                Handlevogn hv = new Handlevogn();
                hv.varer = new List<HandlevognItem>();
                Session["Handlevogn"] = hv;
            }
            if (Session["LoggetInn"] == null)
            {
                Session["LoggetInn"] = false;
                ViewBag.Innlogget = false;
            }
            else
            {
                
                ViewBag.Innlogget = (bool)Session["LoggetInn"];

            }
            var vareDb = new VareBLL();
            List<Kategori> alleKat = vareDb.getAllCategories();
            return View(alleKat);
           
        }

        public ActionResult BrowseCategories()
        {
            var vareDb = new VareBLL();
            List<Kategori> alleVarer = vareDb.getAllCategories();
            return View(alleVarer);
        }

        public ActionResult Browse(string kategori)
        {
            //return kategori;
            var vareDb = new VareBLL();
            List<Vare> alleVarer = vareDb.getAllByCategory(kategori);
            return View(alleVarer);
        }

        public ActionResult VareDetail(int vareID)
        {
            var vareDb = new VareBLL();
            Vare enVare = vareDb.getSingleGoods(vareID);
            return View(enVare);
        }

        public ActionResult Handlevogn()
        {
            if (Session["Handlevogn"] == null)
            {
                Session["Handlevogn"] = new Handlevogn();
                Handlevogn handlevogn = ((Handlevogn)Session["Handlevogn"]);
                handlevogn.varer = new List<HandlevognItem>();
            }
            else
            {
                ((Handlevogn)Session["Handlevogn"]).calculateSumTotal();
            }


            return View(((Handlevogn)Session["Handlevogn"]));
        }

        public ActionResult AddToCart(int vareID)
        {
            
            if(Session["Handlevogn"] == null)
            {
                Session["Handlevogn"] = new Handlevogn();
            }
            var vareDb = new VareBLL();
            Vare vare = vareDb.getSingleGoods(vareID);

            Handlevogn handlevogn = ((Handlevogn)Session["Handlevogn"]);
            if (handlevogn.varer != null)
            {
                handlevogn.calculateSumTotal();
                var funnetVare = handlevogn.varer.FirstOrDefault(h => h.Vare.id == vareID);
                if (funnetVare == null)
                {
                    HandlevognItem hv1 = new HandlevognItem();
                    
                    hv1.Vare = vare;
                    hv1.Antall = 1;
                    handlevogn.varer.Add(hv1);
                }
                else
                {
                    funnetVare.Antall++;
                }

            }
            else
            {
                HandlevognItem hv1 = new HandlevognItem();
                hv1.Vare = vare;
                hv1.Antall = 1;
                handlevogn.varer.Add(hv1);
            }
           // return View(((Handlevogn)Session["Handlevogn"]).varer);
            return RedirectToAction("Handlevogn", "Home");
        }

        public ActionResult FjernHandlevognLinje(int vareID)
        {
            if (Session["Handlevogn"] == null)
            {
                Session["Handlevogn"] = new Handlevogn();
            }
          

            Handlevogn handlevogn = ((Handlevogn)Session["Handlevogn"]);
            var slettVare = handlevogn.varer.FirstOrDefault(h => h.Vare.id == vareID);
            if (slettVare != null)
            {
                handlevogn.varer.Remove(slettVare);
            }
            return RedirectToAction("Handlevogn", "Home");
            
        }
        public ActionResult EndreAntallAvVare(int vareID, int antall)
        {
            Handlevogn hv = (Handlevogn)Session["Handlevogn"];
            HandlevognItem hvi = hv.varer.FirstOrDefault(k=> k.Vare.id == vareID);
            hvi.Antall = antall;
            return RedirectToAction("Handlevogn");
            /*;
            if (Session["Handlevogn"] == null)
            {
                Session["Handlevogn"] = new Handlevogn();
            }vi


            Handlevogn handlevogn = ((Handlevogn)Session["Handlevogn"]);
            var endreVare = handlevogn.varer.FirstOrDefault(h => h.Vare.id == vareID);
            if (endreVare != null)
            {
                endreVare.Antall = antall;
            }
            return RedirectToAction("Handlevogn", "Home");*/

        }
    }
}

WebStoreDALBLL/WebStoreDALBLL/Views/Home/AddToCart.cshtml
@model List<WebStoreDALBLL.Models.HandlevognItem>


<h2>Din Handlekurv</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Vare.navn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Antall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Vare.pris)
        </th>
        <th>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Vare.navn)
        </td>
        <td>

            @Html.DisplayFor(modelItem => item.Antall)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vare.pris)
            
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

    <tr>
        <td>
            <p>Sum total:</p>
        </td>
        <td>

        </td>
        <td>
           
        </td>
    </tr>
</table>

WebStoreDALBLL/WebStoreDALBLL/Views/Home/Browse.cshtml
@model List<WebStoreDALBLL.Models.Vare>

<h2>@Model[0].kategori</h2>

@foreach (var item in Model)
{
    <div class="row table-bordered">
        <div class="col-md-6">
            @Html.ActionLink(((item.navn) + " , " + (item.pris) + "kr"),
               "VareDetail", "Home", new { vareID = item.id }, new { @class = "h4" })
        
            <a href="@Url.Action("VareDetail", "Home", new { vareID = item.id })"> <img src="@item.photoURL" height="20" class="img-responsive img-thumbnail" /></a>

</div>
    </div>
}

    

WebStoreDALBLL/WebStoreDALBLL/Views/Home/BrowseCategories.cshtml
@model IEnumerable<WebStoreDALBLL.Models.Kategori>


<h2>Kategorier</h2>


<ul>
@foreach (var item in Model)
{

    <li>
        
        @Html.ActionLink(item.navn, "Browse", "Home", new { kategori = item.navn }, new { @class="h3"})
        <a href="@Url.Action("Browse","Home", new { kategori = item.navn })"> <img src="@item.photoURL" height="128" /></a>
        
    </li>

}
</ul>

WebStoreDALBLL/WebStoreDALBLL/Views/Home/Handlevogn.cshtml
@model WebStoreDALBLL.Models.Handlevogn


<h2>Din Handlekurv</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.varer[0].Vare.navn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.varer[0].Antall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.varer[0].Vare.pris)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model.varer)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vare.navn)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.Antall, new { @id = (item.Vare.id +"l") })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vare.pris)

            </td>
            
            <td>
               
                @Html.ActionLink("Edit", "EndreAntallAvVare",  new { vareID = item.Vare.id, antall = (item.Vare.id+"l") } ) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Slett", "FjernHandlevognLinje", new { vareID=item.Vare.id})
            </td>
        </tr>
    }
    <tr class="bg-info">
        <td>
            <strong>Sum total:</strong>
        </td>
        <td></td>
        
        <td><strong>@Html.DisplayFor(model => model.prisTotal)</strong></td>
    </tr>

   
</table>
@Html.ActionLink("Til kassen", "RegisterOrder", "Bestilling")

WebStoreDALBLL/WebStoreDALBLL/Views/Home/Index.cshtml
@model List<WebStoreDALBLL.Models.Kategori>

<div class="jumbotron">
    <h1>Velkommen til vår lille butikk</h1>
    <p class="lead">Her vil vi lage vår lille test instrument Butikk</p>
</div>

<div class="row">

        @foreach (var item in Model)
        {

            <div class="col-md-3">
                <div>
                    <a href="@Url.Action("Browse","Home", new { kategori = item.navn })">
                         <img src="@item.photoURL" height="128"  class="img-thumbnail" />
                    </a>
</div>
                <div class="text-center">
                    @Html.ActionLink(item.navn, "Browse", "Home", new { kategori = item.navn }, new { @class = "h3" })
                </div>
            </div>
        }
    </div>

WebStoreDALBLL/WebStoreDALBLL/Views/Home/VareDetail.cshtml
@model WebStoreDALBLL.Models.Vare
<div class="row">
    <div class="col-lg-4">
        <h4>Vare</h4>
        <hr />
        <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.navn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.navn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pris)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pris)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kvantitet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kvantitet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.beskrivelse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.beskrivelse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.produsent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.produsent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kategori)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kategori)
        </dd>
       

        </dl>

        <p>
            @Html.ActionLink("Legg i handlevognen", "AddToCart", new { vareID = Model.id }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Tilbake", "BrowseCategories")
        </p>
    </div>



    <div class="col-lg-1 ">
        
        <br />
        <br />
        <br />
        <br />
                <img src="@Model.photoURL" width="400"  />
           
    </div>
</div>