WebStoreDALBLL/WebStoreDALBLL/Controllers/KundeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreDALBLL.BLL;
using WebStoreDALBLL.Models;

namespace WebStoreDALBLL.Controllers
{
    public class KundeController : Controller
    {
        // GET: Kunde
        public ActionResult Index()
        {
            if (Session["LoggetInn"] == null)
            {
                Session["LoggetInn"] = false;
                ViewBag.Innlogget = false;
            }
            else
            {
                ViewBag.Innlogget = (bool)Session["LoggetInn"];
            }

         

            return View();
        }

        public ActionResult RegisterNew()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterNew(Kunde innKunde)
        {
            if (ModelState.IsValid)
            {
                var kundeDb = new KundeBLL();
                bool insertOK = kundeDb.insertCustomer(innKunde);
                if (insertOK)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }


        // GET: Bruker
       


        // GET: /Bruker/LoggUt
        public ActionResult LoggUt()
        {
            Session["LoggetInn"] = false;
            Session["Bruker"] = null;
            Handlevogn hv = (Handlevogn)Session["Handlevogn"];
            hv.kunde = null;
            return RedirectToAction("Index", "Home");
        }

        // GET: /Bruker/LoggInn
        public ActionResult LoggInn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoggInn(FormCollection innListe)
        {
            var brukernavn = innListe["Epost"];
            var passord = KundeBLL.hashPword(innListe["Passord"]);
            try
            {
                var db = new KundeBLL();
                var funnetBruker = db.getSingleCustomerByEmail(brukernavn);
                
               
                    if (funnetBruker == null)
                    {
                        return View();
                    }
                    else
                    {
                        if (funnetBruker.hashPassord.SequenceEqual(passord))
                        {
                            Session["LoggetInn"] = true;
                            Session["Bruker"] = funnetBruker;
                         Handlevogn handlevogna = (Handlevogn)Session["Handlevogn"];
                            handlevogna.kunde = funnetBruker;
                            return RedirectToAction("Index", "Home");
                            // return "Kundenr: " + ((Kunde)Session["Bruker"]).KundeNR + " | Brukernavn: " + ((Kunde)Session["Bruker"]).Epost + " er logget inn!";
                        }
                        //return "funnetBruker.Passord: " + funnetBruker.Passord + " | innskrevet hash: " + passord;
                    }
                
                return View();
            }
            catch (Exception feil)
            {

                return View(feil);
            }
        }
        
        public ActionResult MinSide()
        {
            Kunde deg = (Kunde)Session["Bruker"];
            return View(deg);
        }
    
        public ActionResult MineOrdrer()
        {
            Kunde deg = (Kunde)Session["Bruker"];
            var ordreliste = new BestillingsBLL();
            var utdata = ordreliste.getAllOrders(deg.id);
            return View(utdata);
        }

        public ActionResult DetailsOrder(int id)
        {
            var BestillingsDb = new BestillingsBLL();
            Bestilling enBestilling = BestillingsDb.getSingleBestilling(id);

            return View(enBestilling);

        }

        public ActionResult EndreBruker(int id)
        {
            Kunde innlogget = (Kunde)Session["Bruker"];
            var kundeDb = new KundeBLL();
            Kunde enKunde = kundeDb.getSingleCustomer(innlogget.id);
            return View(enKunde);
        }

        [HttpPost]
        public ActionResult EndreBruker(int id, Kunde endreKunde)
        {
         
            if (ModelState.IsValid)
            {
                var kundeDb = new KundeBLL();
                bool endringOK = kundeDb.changeCustomer(id, endreKunde);
                if (endringOK)
                {
                    return RedirectToAction("MinSide");
                }
            }
            return View();
        }
    }
}

WebStoreDALBLL/WebStoreDALBLL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/dropzone/dropzone.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Scripts/dropzone/dropzone.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebStoreDALBLL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right list-inline">
                    <li>
                        <a href="@Url.Action("BrowseCategories", "Home")">
                          Vis varer
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Handlevogn", "Home")">
                            <i class="glyphicon glyphicon-shopping-cart"> </i> Handlekurv
                        </a>
                    </li>
                    @if (Session["Bruker"] != null)
                    {
                        <li>
                            <a href="@Url.Action("MinSide", "Kunde")">MinSide</a>
                            </li>

                        <li>
                            <strong class="navbar-text">
                                Du er logget inn som:
                                <!--Henter referanse til Kunde klassen for å kunne hente ut navn og kundenr til innlogget bruker-->
                                @{WebStoreDALBLL.Models.Kunde kunde = (WebStoreDALBLL.Models.Kunde)Session["Bruker"];}
                                @kunde.fornavn @kunde.etternavn - @kunde.id
                            </strong>
                        </li>
                        <li><a href="/Kunde/LoggUt">Logg ut</a></li>
                    }
                    else
                    {
                        <li><a href="/Kunde/LoggInn">Logg inn / Registrer deg</a></li>
                    }
                </ul>
               
            </div>
          
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                <a href="@Url.Action("Index", "Admin")">adminpage</a>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>